### ISSUE TITLE
FM-4: Create base template for app

### ISSUE THREAD

**Issue by IvanYukish** [IvanYukish/finance-manager#6]
We need to create base architecture for our js, and css folders (like templates), also we need to provide base styles (some normalization for browser consistency ). I recommend use this tutorial https://purecss.io/base/.

**Comment by muclaud** [comment]
Got it. if will be additional questions, I will write

**Comment by IvanYukish** [comment]
Hi Taras, after that when you push your branch, you need create Pull Request to master branch, assign me, and in comment should be written "solves #issue_number".

**Comment by IvanYukish** [comment]
if you need some help, write me
